package com.example.ui.components

import com.example.data.model.PromptConfig

object CodeGenerator {

    fun generateKotlin(prompt: String, config: PromptConfig): String {
        val sysInstructionBlock = if (config.systemInstruction.isNotBlank()) {
            """
        systemInstruction = Content(
            parts = listOf(Part(text = "${escape(config.systemInstruction)}"))
        ),"""
        } else ""

        val thinkingBlock = if (config.thinkingLevel != "none" && config.modelId.contains("pro")) {
            """
            thinkingConfig = ThinkingConfig(thinkingLevel = "${config.thinkingLevel}"),"""
        } else ""

        val jsonBlock = if (config.isJsonOutput) {
            """
            responseMimeType = "application/json","""
        } else ""

        return """// Kotlin (Android Jetpack Compose / Retrofit)
// Generated by Google AI Studio
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

suspend fun callGemini(): String = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    val request = GenerateContentRequest(
        contents = listOf(
            Content(role = "user", parts = listOf(Part(text = "${escape(prompt)}")))
        ),$sysInstructionBlock
        generationConfig = GenerationConfig(
            temperature = ${config.temperature}f,
            topP = ${config.topP}f,
            topK = ${config.topK},
            maxOutputTokens = ${config.maxOutputTokens},$thinkingBlock$jsonBlock
        )
    )

    val response = ApiClient.service.generateContent(
        model = "${config.modelId}",
        apiKey = apiKey,
        request = request
    )
    response.candidates?.firstOrNull()?.content?.parts?.joinToString("\n") { it.text ?: "" } ?: ""
}"""
    }

    fun generatePython(prompt: String, config: PromptConfig): String {
        val sysParam = if (config.systemInstruction.isNotBlank()) {
            """
        system_instruction="${escape(config.systemInstruction)}","""
        } else ""

        val jsonParam = if (config.isJsonOutput) {
            """
        response_mime_type="application/json","""
        } else ""

        return """# Python (google-genai SDK)
# Generated by Google AI Studio
# pip install google-genai

import os
from google import genai
from google.genai import types

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

response = client.models.generate_content(
    model="${config.modelId}",
    contents="${escape(prompt)}",
    config=types.GenerateContentConfig(
        temperature=${config.temperature},
        top_p=${config.topP},
        top_k=${config.topK},
        max_output_tokens=${config.maxOutputTokens},$sysParam$jsonParam
    ),
)

print(response.text)"""
    }

    fun generateJavaScript(prompt: String, config: PromptConfig): String {
        val sysParam = if (config.systemInstruction.isNotBlank()) {
            """
      systemInstruction: "${escape(config.systemInstruction)}","""
        } else ""

        val jsonParam = if (config.isJsonOutput) {
            """
      responseMimeType: "application/json","""
        } else ""

        return """// JavaScript / TypeScript (@google/genai SDK)
// Generated by Google AI Studio
// npm install @google/genai

import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

async function run() {
  const response = await ai.models.generateContent({
    model: "${config.modelId}",
    contents: "${escape(prompt)}",
    config: {
      temperature: ${config.temperature},
      topP: ${config.topP},
      topK: ${config.topK},
      maxOutputTokens: ${config.maxOutputTokens},$sysParam$jsonParam
    },
  });

  console.log(response.text);
}

run();"""
    }

    fun generateCurl(prompt: String, config: PromptConfig): String {
        val sysJson = if (config.systemInstruction.isNotBlank()) {
            """,\n    "systemInstruction": {"parts": [{"text": "${escape(config.systemInstruction)}"}]}"""
        } else ""

        val mimeJson = if (config.isJsonOutput) {
            """,\n      "responseMimeType": "application/json""""
        } else ""

        return """# cURL REST API Request
# Generated by Google AI Studio

curl -X POST "https://generativelanguage.googleapis.com/v1beta/models/${config.modelId}:generateContent?key=${'$'}GEMINI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "contents": [
      {
        "role": "user",
        "parts": [{"text": "${escape(prompt)}"}]
      }
    ]$sysJson,
    "generationConfig": {
      "temperature": ${config.temperature},
      "topP": ${config.topP},
      "topK": ${config.topK},
      "maxOutputTokens": ${config.maxOutputTokens}$mimeJson
    }
  }'"""
    }

    private fun escape(text: String): String {
        return text.replace("\"", "\\\"").replace("\n", "\\n")
    }
}
